I=imread('pappers.png');%%读取图像
imshow(I);%%显示原图
title('原图');
figure,imhist(I);
title('原图像的直方图');
J1=imadjust(I,[0.3,0.7],[]);
figure,imshow(J1);
title('输出图像的效果图');
figure,imhist(J1);
title('输出图像的直方图');