figure(1);
subplot(2,2,[1 3]);
margin(tf1);
title('仿真系统频率特性');
subplot(2,2,2);
plot(F,A);
title('实际系统幅频特性曲线');
subplot(2,2,4);
plot(F,P);
title('实际系统相频特性曲线');
figure(2);
subplot(2,2,[1 3]);
margin(tf2);
title('仿真系统频率特性');
subplot(2,2,2);
plot(F2,A2);
title('实际系统幅频特性曲线');
subplot(2,2,4);
plot(F2,P2);
title('实际系统相频特性曲线');