RGB=imread('pappers.png');%%读取papper图像文件
R=RGB(:,:,1);
G=RGB(:,:,2);
B=RGB(:,:,3);
subplot(2,2,1);%%把界面分成2*2块，该图形占据第一块
imshow(RGB);
title('原始图像');
subplot(2,2,2);%%占据第二块
imshow(R);
title('R分量图像');
subplot(2,2,3);%%占据第三块
imshow(G);
title('G分量图像');
subplot(2,2,4);%%占据第四块
imshow(B);
title('B分量图像');